"""added profile fields

Revision ID: 222e106a2e9b
Revises: 377fbca88241
Create Date: 2026-03-13 21:10:02.621233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222e106a2e9b'
down_revision = '377fbca88241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform_fee', sa.Integer(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('developer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('developer_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('commission')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('commission', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('developer_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('developer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('platform_fee')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
