"""added profile fields

Revision ID: 377fbca88241
Revises: 66cc920954ca
Create Date: 2026-03-07 12:51:42.405556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377fbca88241'
down_revision = '66cc920954ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('resume', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume')
        batch_op.drop_column('github')
        batch_op.drop_column('bio')
        batch_op.drop_column('skills')

    op.drop_table('project_file')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
