"""added profile fields

Revision ID: 54378cb7bf6e
Revises: c97bebecf3aa
Create Date: 2026-03-17 17:49:34.123571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54378cb7bf6e'
down_revision = 'c97bebecf3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_withdraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_withdraw')
    # ### end Alembic commands ###
